---
  apiVersion: helm.integrations.flux.weave.works/v1alpha2
  kind: FluxHelmRelease
  metadata:
    name: kube-prometheus
    namespace: monitoring
    labels:
      chart: kube-prometheus
      test: "true"
  spec:
    chartGitPath: kube-prometheus
    values: {}
